### PR TITLE
Enforce JSON data types on select nodes

### PR DESCRIPTION
**Pull request by rimutaka**
Work in progress.  Relates to  issue #6. Deployed to one prod environment for testing.

See this section of diff in ReadMe for detailed explanation https://github.com/AlecTroemel/quickxml_to_serde/compare/master...rimutaka:master#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R41

## Changes

1. Added a config property to map xml paths to JSON data types
2. Added `JsonType` enum
3. Updated `basic.rs` example. We might need another example for this new feature
4. Added `json_types` feature to Cargo.toml
5. Added path tracking and JSON type selection to `fn convert_node()`, conditional on `json_types` feature being enabled.
Not the most elegant solution there. I was thinking of making a macro or a small function for that, but the gains are small.
6. Updated test cases
7. Updated embedded docs and readme
8. Added 2 sample XML docs for issue #9. It's non-consequential, but they probably should go into a different PR. Just noticed they got lumped up into this change.
9. Bumped the version to 4.2
10. Added an example file

Since most of the changes are conditional on enabling `json_types` feature there is no performance impact on existing implementations. The additional code that tracks the path during XML tree traversal:
```rust
    let path = [path, "/", el.name()].concat();
    let json_type = config.json_type_overrides.get(&path).unwrap_or(&config.json_type);
```

`config.json_type_overrides` is a HashMap. I wonder if BTreeMap is a better choice. I have not done any benchmarks.

## Breaking changes 

- **IMPORTANT**: removed `v != 0` from `fn parse_text()`, which may affect backward compatibility.
see https://github.com/AlecTroemel/quickxml_to_serde/compare/master...rimutaka:master#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R196

### CODE REVIEW

**Comment by AlecTroemel** [comment]
@rimutaka good changes. I'm still digging into the `v != 0` concern, so I'm not sure whether to keep it or remove it yet. I could be wrong, but I doubt we'll see much difference between `HashMap` and `BTreeMap` since they'll most likely stay relatively small in use. 

Also, although we're not following semantic versioning perfectly, I'd vote to have this PR bump the version up to `0.5.0` since it both adds new features and breaking changes. I'd like to reserve PATCH versions for backwards compatible bug fixes.

**Comment by AlecTroemel** [comment]
alright, so I think the `v != 0` handles the case where the value is `0`. Without that addition check, it would be become the string "0" instead of a number. When you remove it this assert fails

```rust
assert_eq!(0, parse_text("0", true)); // fails without v != 0
```

I think we could check if the length of  the text is greater then 1, since something can only "start with" 0 if something else comes after it!

```rust
if let Ok(v) = text.parse::<u64>() {
        // don't parse octal numbers and those with leading 0
        if text.len() > 1 && text.starts_with("0") && leading_zero_as_string {
            return Value::String(text.into());
        }
        return Value::Number(Number::from(v));
    }
```

if we do that then these asserts pass

```rust
assert_eq!(0, parse_text("0", true));
assert_eq!("00", parse_text("00", true));
```

**Comment by rimutaka** [comment]
I removed the breaking change and added an example file. The combined diff is smaller now. I guess v 0.4.2 is more appropriate now - we added an optional feature.

Re `v!=0` check ... 

It would produce inconsistent result in an example like this `{ "a": ["03", "02", "01", 0] }

Is there a practical application for `assert_eq!(0, parse_text("0", true));`?
I would think it should be `assert_eq!("0", parse_text("0", true));`, but there may be a use case I'm not aware of.

Thinking, we can leave that `v != 0` check in. It doesn't make much difference. If someone wants to enforce strings it can be done via the new method with XML paths. It will be safer for anyone upgrading from the prev version too.

**Comment by AlecTroemel** [comment]
LGTM!

**Pull request merged**
