### PR TITLE
Don't parse numbers with leading zero

### PR DESCRIPTION
**Pull request by Dgame**

### CODE REVIEW

**Comment by AlecTroemel** [comment]
@MariusRumpf thanks for the PR! What use case are you thinking of for this? If I understand correctly this would  preserve `01234` as a string instead of parsing it into the number `1234` right?

**Comment by MariusRumpf** [comment]
@AlecTroemel That is correct. 
We have a use case where external services return the xml entry with leading zeros. These are used as identifiers and the leading zero is important to identify a single dataset coming from other sources too.   
We also thought about a case where an octal number was given, starting with `0x`, is this interpreted as number?

**Comment by AlecTroemel** [comment]
@MariusRumpf sorry about the delay on this. Some code I have that uses this depends on parsing numbers with leading zeros as numbers, so my thought is to introduce a `config` struct to turn this on or off. I pulled your branch and added that here https://github.com/AlecTroemel/quickxml_to_serde/tree/octol. Let me know if that works for you!

**Comment by rimutaka** [comment]
I included this change in PR #5

**Pull request merged**
